### ISSUE TITLE
Wercker Android

### ISSUE THREAD

**Issue by abdymalikmulky** [wercker/box-android#22]
i try to user wercker for android with this 
https://github.com/wercker/box-android

i get an error

> Error interacting with this repository: docker.io/wercker/android GET https://registry.hub.docker.com/v1/repositories/wercker/android/images returned 404

**Comment by hatchan** [comment]
This box only works with the legacy stack. It looks like you are using the Docker stack, so you need to use a Docker image from the Docker Registry or a private registry. https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=android&starCount=0
